# Generated by Django 6.0.4 on 2026-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
