# Generated by Django 6.0.4 on 2026-04-27 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_itempedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('rua', models.CharField(blank=True, default='', max_length=200)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
