# Generated by Django 6.0.4 on 2026-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_pedido_cliente_perfilcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
