# Generated by Django 6.0.4 on 2026-04-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_pedido_frete_pedido_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, default='💎', help_text='Emoji do ícone', max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='tamanho',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('acessorio', 'Acessório geral'), ('anel', 'Anel'), ('brinco', 'Brinco'), ('colar', 'Colar'), ('pulseira', 'Pulseira'), ('tornozeleira', 'Tornozeleira')], default='acessorio', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='loja.categoria'),
        ),
        migrations.CreateModel(
            name='TamanhoAnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 14, 15, 16, 17, 18', max_length=5)),
                ('estoque', models.IntegerField(default=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['numero'],
            },
        ),
    ]
