# Generated by Codex on 2026-05-02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_pedido_melhor_envio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='aceita_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrinho',
            name='telefone_cliente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='whatsapp_abandono_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='whatsapp_abandono_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
