# Generated by Django 6.0.4 on 2026-05-07

from django.db import migrations, models


def criar_cupom_teste_frete(apps, schema_editor):
    Cupom = apps.get_model('loja', 'Cupom')
    Cupom.objects.update_or_create(
        codigo='TESTEFRETE',
        defaults={
            'tipo': 'frete_gratis',
            'valor': 0,
            'ativo': True,
            'uso_maximo': 0,
            'valor_minimo': 0,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_poscompra_abandono_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('percentual', 'Percentual'),
                    ('valor', 'Valor fixo'),
                    ('frete_gratis', 'Frete grátis'),
                ],
                default='percentual',
                max_length=20,
            ),
        ),
        migrations.RunPython(criar_cupom_teste_frete, migrations.RunPython.noop),
    ]
