# Generated by Django 6.0.4 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0019_alter_cupom_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliques',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de acessos na pagina do produto.'),
        ),
    ]
