# Generated by Django 6.0.4 on 2026-05-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_pedido_meta_purchase_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
