# Generated by Django 6.0.4 on 2026-05-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_produto_imagem_2_produto_imagem_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('destinatario_nome', models.CharField(blank=True, default='', max_length=120)),
                ('assunto', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-mail pendente',
                'verbose_name_plural': 'E-mails pendentes',
                'ordering': ['criado_em'],
            },
        ),
    ]
