# Generated by Django 6.0.4 on 2026-05-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_emailpendente'),
        ('otp_static', '0003_add_timestamps'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoTOTP',
            fields=[
            ],
            options={
                'verbose_name': 'Dispositivo TOTP (2FA)',
                'verbose_name_plural': 'Dispositivos TOTP (2FA)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.CreateModel(
            name='TokenEmergencia',
            fields=[
            ],
            options={
                'verbose_name': 'Token de emergência',
                'verbose_name_plural': 'Tokens de emergência',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_static.staticdevice',),
        ),
    ]
