# Generated by Django 6.0.4 on 2026-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_alter_carrinho_atualizado_em_alter_pedido_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origem_utm',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros utm_*, gclid e fbclid da última visita.'),
        ),
    ]
