# Generated by Django 6.0.4 on 2026-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_pedido_origem_utm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, default='', help_text='Instruções do cliente: embrulho de presente, observações de entrega, etc.', max_length=500),
        ),
    ]
