# Generated by Django 6.0.4 on 2026-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0029_pedido_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=20)),
                ('aceita_whatsapp', models.BooleanField(default=True)),
                ('origem', models.CharField(default='home', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['sessao_key', 'telefone'], name='loja_lead_sessao__e73847_idx')],
            },
        ),
    ]
