# Generated by Django 6.0.4 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0030_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peso_gramas',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text='Peso unitario da peca em gramas. Se vazio, usamos 8g como padrao no calculo de frete.',
            ),
        ),
    ]
