# Generated by Django 6.0.4 on 2026-06-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0031_produto_peso_gramas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do carrinho', 'verbose_name_plural': 'Itens do carrinho'},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto', 'tamanho')},
        ),
    ]
