# Generated by Django 6.0.4 on 2026-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0032_add_itemcarrinho_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddIndex(
            model_name='emailpendente',
            index=models.Index(fields=['status', 'criado_em'], name='loja_emailp_status_07e787_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['visivel', '-criado_em'], name='loja_produt_visivel_5c02c5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['visivel', 'destaque'], name='loja_produt_visivel_e7a50c_idx'),
        ),
    ]
