# Generated by Django 6.0.4 on 2026-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0033_perf_indexes_produto_emailpendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de crédito'), ('boleto', 'Boleto bancário')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.CharField(blank=True, default='', help_text='Instruções do cliente: embrulho de presente, observações de entrega, etc.', max_length=500),
        ),
    ]
