# Generated by Django 6.0.4 on 2026-06-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0035_cupom_so_clientes_fidelidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cupom',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='usado_em_pedido',
            field=models.ForeignKey(blank=True, help_text='Pedido em que o cupom deste lead foi utilizado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_cupom', to='loja.pedido'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telefone', 'cupom'], name='loja_lead_telefon_c61ff0_idx'),
        ),
    ]
