# Generated by Django 6.0.4 on 2026-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0037_cupom_primeira10'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto_pix_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
