# Generated by Django 6.0.4 on 2026-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0038_desconto_pix_aplicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pendente', 'Não informado'), ('pix', 'PIX'), ('cartao', 'Cartão de crédito'), ('boleto', 'Boleto bancário')], db_index=True, max_length=20),
        ),
    ]
