# Generated by Django 6.0.4 on 2026-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0039_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='frete_transportadora',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lalamove_order_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lalamove_quotation_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lalamove_tracking_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_lalamove',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
