# Generated by Django 6.0.4 on 2026-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0040_pedido_lalamove_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao_categoria',
            field=models.TextField(blank=True, default='', help_text='Texto introdutório exibido no topo da página da categoria (bom para SEO). Pode ficar vazio por enquanto.'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Resumo para Google, até 160 caracteres. Se vazio, usamos uma descrição automática.', max_length=160),
        ),
        migrations.AddField(
            model_name='categoria',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Título customizado para Google/aba do navegador. Se vazio, usamos um título automático.', max_length=70),
        ),
    ]
